### PR TITLE
big refactoring and additions

### PR DESCRIPTION
**Pull request by s-light**
Hello silverslade,

in my last customer project i used blender, your exporter addon and aframe heavily...
and i needed a bunch of chagnes / additions.....

i have refactored most of the code for easier reading / splitted it in multiple files..
(maybe there is some more potential for splitting...)
i used black to format all files.

today i have rebased my changes on your master branch and reimplemented some of the things just on top of my changes..
- [reimplement light handling](https://github.com/silverslade/aframe_blender_exporter/commit/ef4bae44b4e1a8d1214e002fdcb98949fcece71d)
- [reimplement export_single_model](https://github.com/silverslade/aframe_blender_exporter/commit/50e334dd4fbbca7664c38b1bfd175de4bb819d69)
are not tested yet...

i hope that someone finds this additons usefulle - and maybe you accept this very big pullrequest...
(i know it is not the *smothest way* to just request such a big change... - in the first place it was just a *quick - i have to get it working for the project....* )

sunny greetings
stefan

### CODE REVIEW

**Comment by s-light** [comment]
~on addition:
currently i have tested it with blender 3.1. beta -
and also with the 3.1-vtree branch of the gltf exporter..~

~i hope that i find some time this week to test with blender 3.0.~
now tested and working on official blender 3.1.0.

**Comment by SanctumVenture** [comment]
```
Python: Traceback (most recent call last):
  File "C:\Users\llill\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\aframe_blender_exporter-dev_rebase\__init__.py", line 507, in execute
    return my_exporter.export()
  File "C:\Users\llill\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\aframe_blender_exporter-dev_rebase\export_aframe\__init__.py", line 1095, in export
    self.export_single_model()
  File "C:\Users\llill\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\aframe_blender_exporter-dev_rebase\export_aframe\__init__.py", line 803, in export_single_model
    filename = os.path.join(constants.DEST_RES, constants.PATH_ASSETS, "MainMesh")
AttributeError: module 'aframe_blender_exporter-dev_rebase.constants' has no attribute 'DEST_RES'

location: <unknown location>:-1
```

Error activating export single GLTF model.
os: Windows 11
Blender version: 3.1

**Comment by s-light** [comment]
thanks for reporting - i will have a look.

**Comment by SanctumVenture** [comment]
fixed on: 8b3c8ebfa0480dbabf8b8073c75a48afc4dbcb1e

**Comment by s-light** [comment]
thanks @SanctumVenture for fixing.

i just improved / added relative-path handling..
and with this fixed also the default *Enviroment Texture* handling
and tested all this in the current official 3.1.0 version.

please report here or as issue if there are other things that do not work!

**Comment by silverslade** [comment]
Hi s-light,
thanks for the Pull Request.
I think this is a huge refactoring, I've tried to install your version into Blender 3.0.0 but it fails to install.
There are too many updates since the last release version.

Drop me a line to manage how to merge your updates.

**Comment by s-light** [comment]
hi Alessandro,

thanks for trying - i only tested it in the [currently official `Blender 3.1.0`](https://www.blender.org/download/) -
i personally think it is fine to define 3.1.0 as the minimum version.
it brings some great improvements in the gltf exporter...

do you think support for `3.0.0` is essential?
than i will try to tweak this..

**Comment by kylebakerio** [comment]
Bump on this, would love to see this merged.

**Comment by kylebakerio** [comment]
btw, though, stable on Pop OS (and therefore same or earlier on Debian and Ubuntu) is blender 3.0, not 3.1. Still, if this was a thing, I'd consider building 3.1 from src.

**Comment by kylebakerio** [comment]
As it is, the repo has fallen enough out of date that it's going to not be worth using if something isn't done--sounds like for better or worse, this is probably the way to go.

It's such a cool project, it would be a shame for it to just die.
